### ISSUE TITLE
How do you do a group by and join together with SQL ? 

### ISSUE THREAD

**Issue by shindesimantini6** [shindesimantini6/REDI_Data_Analytics_Git_class#2]
I am trying to group by with aggregating count and join two datasets, does anyone know how can I ?

**Comment by MiraySardogan** [comment]
first, you can join the datasets with a common column, then group by.

**Comment by nms289** [comment]
You can use GROUP BY with INNER JOIN in SQL

**Comment by shindesimantini6** [comment]
@MiraySardogan Let me give it shot and I will let you know.

**Comment by saamehg** [comment]
select count(t1.col1), t1.col2, t2.col2
from dataset1 as t1
join dataset2 as t2
group by 2,3

**Comment by shindesimantini6** [comment]
Kool thanks prob solved
